// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...a
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_skz1dfPOssXtgLST2hsjCXMJ50ZCxow',
    appId: '1:661106763380:web:96f08062dabc768cd29321',
    messagingSenderId: '661106763380',
    projectId: 'dairy-app-43710',
    authDomain: 'dairy-app-43710.firebaseapp.com',
    storageBucket: 'dairy-app-43710.firebasestorage.app',
    measurementId: 'G-R7LKQQXMMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUvVEmMpKwcd5jy5iWqUPT1RNher_8AY',
    appId: '1:661106763380:android:ebb577381ab6eb99d29321',
    messagingSenderId: '661106763380',
    projectId: 'dairy-app-43710',
    storageBucket: 'dairy-app-43710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjwn45gZQcmxd-kkyMtkkx_haEQOe4QA8',
    appId: '1:661106763380:ios:8eaf70efa3be4820d29321',
    messagingSenderId: '661106763380',
    projectId: 'dairy-app-43710',
    storageBucket: 'dairy-app-43710.firebasestorage.app',
    iosClientId: '661106763380-2jv0p405fahpgjka942p0sspsgas06o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjwn45gZQcmxd-kkyMtkkx_haEQOe4QA8',
    appId: '1:661106763380:ios:8eaf70efa3be4820d29321',
    messagingSenderId: '661106763380',
    projectId: 'dairy-app-43710',
    storageBucket: 'dairy-app-43710.firebasestorage.app',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_skz1dfPOssXtgLST2hsjCXMJ50ZCxow',
    appId: '1:661106763380:web:a9b261ca3b7d7b71d29321',
    messagingSenderId: '661106763380',
    projectId: 'dairy-app-43710',
    authDomain: 'dairy-app-43710.firebaseapp.com',
    storageBucket: 'dairy-app-43710.firebasestorage.app',
    measurementId: 'G-KSKBCWGZYC',
  );
}